name: Milestone Assessement
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
  TEST_SUITES_URL: https://github.com/Estia-advanced-programming/pandora-public/releases/download/beta/

jobs:
  maven_build:
    name: Maven build
    runs-on: ubuntu-latest
    steps:
      - name: checkout your code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - run: mkdir -p staging/lib && cp target/*.jar staging  && cp target/lib/*.jar staging/lib

      - name: download test suite
        run: |
          wget $TEST_SUITES_URL/autograder.zip -O autograder.zip
          unzip autograder.zip -d autograder

      - uses: actions/setup-node@v2

      - name: create Output directory
        run: mkdir results

      - name: run test
        run: node autograder/execute.mjs 1 2 3 -f 4 staging/pandora.jar

      - name: update report
        if: failure()
        run: echo error

      - name: update report
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: score-report
          path: results/
